export { default as always } from './always';
export { default as compl } from './compl';
export { default as compl3 } from './compl3';
export { compose, default as $ } from './compose';
export { default as flip } from './flip';
export { default as identity } from './identity';
export { default as ite } from './ite';
export { default as pipe } from './pipe';
export { default as _eqTo } from './_eqTo';
export { default as eqTo } from './eqTo';